"""import db in models.py

Revision ID: 00141d366319
Revises: 17c60318b9a7
Create Date: 2020-12-27 04:06:22.681896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00141d366319'
down_revision = '17c60318b9a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
