"""Added items table

Revision ID: 03c1a4d01b21
Revises: f7ce49c9785a
Create Date: 2020-12-27 02:02:16.100795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c1a4d01b21'
down_revision = 'f7ce49c9785a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iems_id'), 'iems', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iems_id'), table_name='iems')
    op.drop_table('iems')
    # ### end Alembic commands ###
