"""db back to main.py

Revision ID: fd769291ee31
Revises: 00141d366319
Create Date: 2020-12-27 04:11:07.598009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd769291ee31'
down_revision = '00141d366319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
